spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/neighborhood?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: neighborhood
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
  multipart:
    maxFileSiz: 20MB
    maxRequestSize: 20MB